version: '3'

services:
    php-fpm:
        build: .docker/php-fpm
        volumes:
            - .:/var/www:cached
        working_dir: /var/www
    nginx:
        image: nginx:1.25
        ports:
            - 8000:80
        volumes:
            - .docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
###> doctrine/doctrine-bundle ###
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: password
            POSTGRES_USER: app
        volumes:
            - postgres:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
    postgres:
###< doctrine/doctrine-bundle ###
