name: checks

on:
    - push

jobs:
    php_checks:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15-alpine
                env:
                    POSTGRES_PASSWORD: password
                ports:
                    - 5432:5432
                options:
                    --health-cmd pg_isready
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer:v2
            - run: composer install
            - run: composer bin all install
            - run: vendor/bin/phpstan
            - run: vendor/bin/php-cs-fixer fix --dry-run --diff
            - run: bin/console doctrine:database:create -e test
            - run: |
                bin/console doctrine:migrations:migrate -e test --no-interaction
                bin/console doctrine:migrations:migrate 0 -e test --no-interaction
            - run: bin/console doctrine:migrations:migrate -e test --no-interaction
            - run: vendor/bin/phpunit
